name = "NsightSystems"
uuid = "48703650-a05b-4a48-928f-989875de1d11"
version = "1.0.0-DEV"
authors = ["singularitti <singularitti@outlook.com> and contributors"]

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Tables = "1.12.1"
Unitful = "1.22.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
